### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by tyler17**
I tested different transactions and different accounts and everything seems to be working.  I still need to figure out how to test signMessage(), but wanted to get feedback sooner rather than later.  Once it looks good, I can bring these changes into `dai-plugin-trezor-web`.  I wasn't able to find any examples providers online that use the latest trezor connect version.

### CODE REVIEW

**Comment by levity** [comment]
@tyler17 were you able to test this on Kovan as well as local dev?

**Comment by tyler17** [comment]
@levity I tested this on Kovan, didn't do any testing on a testchain.  However, I just noticed that when I select trezor with metamask on Mainnet, it still uses Kovan, so I'm looking into that now.

I'm also thinking it's not necessary to test signMessage() now, as we don't expose that functionality in dai.js (and don't use it in any of our frontends yet)

**Comment by tyler17** [comment]
Nevermind, that 'mainnet' issue is by design per this code here: https://github.com/makerdao/scd-cdp-portal/blob/3d40d8f5a324b687889a3997cf3724bc190f9f29/src/stores/Network.jsx#L125

**Comment by tyler17** [comment]
@levity Does this look good to merge?  Dumitru signed off: https://makerdao.atlassian.net/browse/CDP-219

**Pull request merged**
